name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: WebGoat_Project_v1
          base_uri: https://eu.ast.checkmarx.net
          cx_apikey: ${{ secrets.APIKEY }}
          #cx_client_id: ${{ secrets.CLIENT_ID }}
          #cx_client_secret: ${{ secrets.SECRET }}
          scan_types: sast,kics
